#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for spec 003
# Feature: Low-Code UI/UX Improvements

set -e

echo "========================================"
echo "Starting LogNog Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

echo ""
echo "Checking dependencies..."

if [ ! -d "api/node_modules" ]; then
    echo "Installing API dependencies..."
    cd api && npm install && cd ..
fi

if [ ! -d "ui/node_modules" ]; then
    echo "Installing UI dependencies..."
    cd ui && npm install && cd ..
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# API (Express backend on port 4000)
echo "Starting API..."
cd api && npm run dev &
API_PID=$!
cd ..

# Wait for API to be ready
sleep 2
wait_for_service 4000 "API"

# UI (React frontend on port 3000)
echo "Starting UI..."
cd ui && npm run dev &
UI_PID=$!
cd ..

# Wait for UI to be ready
sleep 3
wait_for_service 3000 "UI"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Development Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  API:  http://localhost:4000"
echo "  UI:   http://localhost:3000"
echo ""
echo "Feature: Low-Code UI/UX Improvements"
echo ""
echo "Files to modify:"
echo "  - api/src/routes/search.ts (execution time)"
echo "  - ui/src/api/client.ts (SearchResult interface)"
echo "  - ui/src/pages/SearchPage.tsx (history, copy JSON, execution time display)"
echo "  - ui/src/components/TimePicker.tsx (relative time tooltips)"
echo ""
echo "Press Ctrl+C to stop all services"
echo "========================================"

# Keep script running
wait
