/**
 * Create HYH Weekly Reports
 *
 * Run with: npx tsx scripts/create-hyh-weekly-reports.ts
 *
 * Creates comprehensive weekly reports for Hey You're Hired:
 * - Weekly Active Users (excluding test accounts)
 * - Weekly Error Summary
 * - Weekly Login Activity
 * - Weekly Feature Usage
 * - Weekly Performance & Health
 */

import Database from 'better-sqlite3';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuidv4 } from 'uuid';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dbPath = join(__dirname, '..', 'lognog.db');

const db = new Database(dbPath);

// Test account patterns to exclude
const TEST_ACCOUNT_EXCLUSION = `NOT user_email LIKE "taskmasterpeace+%" AND NOT user_email LIKE "automation-test@%"`;

// Recipient email - update this!
const RECIPIENTS = process.env.HYH_REPORT_EMAIL || 'team@heyyourehired.com';

// Sunday 9am EST (UTC-5 = 14:00 UTC)
const SUNDAY_9AM_CRON = '0 14 * * 0';

interface ReportConfig {
  id: string;
  name: string;
  description: string;
  query: string;
  schedule: string;
  recipients: string;
  format: string;
  attachment_format: string;
  subject_template: string;
  message_template: string;
  send_condition: string;
  condition_threshold: number | null;
  compare_offset: string | null;
  app_scope: string;
}

const reports: ReportConfig[] = [
  {
    id: uuidv4(),
    name: 'HYH Weekly Executive Summary',
    description: 'High-level metrics for the week: active users, errors, signups, and key trends with week-over-week comparison',
    query: `search index=hey-youre-hired | where ${TEST_ACCOUNT_EXCLUSION} | stats count as total_events, dc(user_email) as unique_users, count(severity<=3) as errors | compare 1w`,
    schedule: SUNDAY_9AM_CRON,
    recipients: RECIPIENTS,
    format: 'html',
    attachment_format: 'csv',
    subject_template: '[HYH] Weekly Executive Summary - {{date:week_of}}',
    message_template: `# Hey You're Hired - Weekly Summary

**Report Period:** {{time_range}}

## Key Metrics

{{#if results}}
{{#each results}}
- **Unique Users:** {{unique_users:comma}}{{#if _change}} ({{_change:+}} vs last week){{/if}}
- **Total Events:** {{total_events:comma}}
- **Errors:** {{errors:comma}}{{#if _change_pct}} ({{_change_pct:percent}} change){{/if}}
{{/each}}
{{else}}
No activity recorded this week.
{{/if}}

---
*Generated by LogNog*`,
    send_condition: 'always',
    condition_threshold: null,
    compare_offset: '1w',
    app_scope: 'hey-youre-hired'
  },
  {
    id: uuidv4(),
    name: 'HYH Weekly Active Users',
    description: 'All non-test accounts that logged in this week with activity counts',
    query: `search index=hey-youre-hired event_type="login" OR event_type="session_start" | where ${TEST_ACCOUNT_EXCLUSION} | stats count as login_count, latest(timestamp) as last_seen by user_email | sort desc login_count`,
    schedule: SUNDAY_9AM_CRON,
    recipients: RECIPIENTS,
    format: 'html',
    attachment_format: 'csv',
    subject_template: '[HYH] Weekly Active Users - {{result_count}} users',
    message_template: `# Weekly Active Users Report

**Week of:** {{date:week_of}}
**Total Active Users:** {{result_count:comma}}

## Most Active Users

{{#each results limit=20}}
| {{user_email}} | {{login_count}} logins | Last: {{last_seen:relative}} |
{{/each}}

{{#if result_count > 20}}
*Showing top 20 of {{result_count}} users. See attached CSV for full list.*
{{/if}}`,
    send_condition: 'if_results',
    condition_threshold: null,
    compare_offset: null,
    app_scope: 'hey-youre-hired'
  },
  {
    id: uuidv4(),
    name: 'HYH Weekly Error Report',
    description: 'Most common errors of the week with counts and examples',
    query: `search index=hey-youre-hired severity<=3 | where ${TEST_ACCOUNT_EXCLUSION} | stats count as error_count, latest(message) as example, latest(timestamp) as last_occurrence by error_type | sort desc error_count | limit 25`,
    schedule: SUNDAY_9AM_CRON,
    recipients: RECIPIENTS,
    format: 'html',
    attachment_format: 'json',
    subject_template: '[HYH] Weekly Errors - {{result_count}} error types',
    message_template: `# Weekly Error Report

**Week of:** {{date:week_of}}
**Error Types Found:** {{result_count}}

{{#if result_count == 0}}
:tada: No errors this week!
{{else}}
## Top Errors

{{#each results limit=10}}
### {{error_type}} ({{error_count:comma}} occurrences)
- **Last seen:** {{last_occurrence:relative}}
- **Example:** \`{{example:truncate:150}}\`

{{/each}}

{{#if result_count > 10}}
*See attached JSON for all {{result_count}} error types.*
{{/if}}
{{/if}}`,
    send_condition: 'always',
    condition_threshold: null,
    compare_offset: null,
    app_scope: 'hey-youre-hired'
  },
  {
    id: uuidv4(),
    name: 'HYH Weekly Signups & Conversions',
    description: 'New signups, trial activations, and conversion metrics',
    query: `search index=hey-youre-hired (event_type="signup" OR event_type="trial_start" OR event_type="subscription_created") | where ${TEST_ACCOUNT_EXCLUSION} | stats count by event_type | compare 1w`,
    schedule: SUNDAY_9AM_CRON,
    recipients: RECIPIENTS,
    format: 'html',
    attachment_format: 'csv',
    subject_template: '[HYH] Weekly Conversions Report',
    message_template: `# Weekly Signups & Conversions

**Week of:** {{date:week_of}}

## Conversion Funnel

{{#each results}}
| **{{event_type}}** | {{count:comma}} | {{#if _change}}{{_change:+}} vs last week{{/if}} |
{{/each}}

{{#if result_count == 0}}
*No conversion events this week.*
{{/if}}`,
    send_condition: 'always',
    condition_threshold: null,
    compare_offset: '1w',
    app_scope: 'hey-youre-hired'
  },
  {
    id: uuidv4(),
    name: 'HYH Weekly Feature Usage',
    description: 'Which features are being used and how often',
    query: `search index=hey-youre-hired event_type="feature_used" | where ${TEST_ACCOUNT_EXCLUSION} | stats count as usage_count, dc(user_email) as unique_users by feature_name | sort desc usage_count | limit 20`,
    schedule: SUNDAY_9AM_CRON,
    recipients: RECIPIENTS,
    format: 'html',
    attachment_format: 'csv',
    subject_template: '[HYH] Weekly Feature Usage',
    message_template: `# Weekly Feature Usage Report

**Week of:** {{date:week_of}}

## Most Used Features

| Feature | Uses | Unique Users |
|---------|------|--------------|
{{#each results}}
| {{feature_name}} | {{usage_count:comma}} | {{unique_users}} |
{{/each}}

{{#if result_count == 0}}
*No feature usage data this week.*
{{/if}}`,
    send_condition: 'if_results',
    condition_threshold: null,
    compare_offset: null,
    app_scope: 'hey-youre-hired'
  },
  {
    id: uuidv4(),
    name: 'HYH Weekly API Health',
    description: 'API response times, error rates, and endpoint performance',
    query: `search index=hey-youre-hired log_type="api_request" | stats count as requests, avg(response_time_ms) as avg_response, p95(response_time_ms) as p95_response, count(status_code>=400) as errors by endpoint | eval error_rate=round(errors/requests*100,2) | sort desc requests | limit 20`,
    schedule: SUNDAY_9AM_CRON,
    recipients: RECIPIENTS,
    format: 'html',
    attachment_format: 'csv',
    subject_template: '[HYH] Weekly API Health Report',
    message_template: `# Weekly API Health Report

**Week of:** {{date:week_of}}

## Endpoint Performance

| Endpoint | Requests | Avg (ms) | P95 (ms) | Error Rate |
|----------|----------|----------|----------|------------|
{{#each results}}
| {{endpoint}} | {{requests:comma}} | {{avg_response:round:0}} | {{p95_response:round:0}} | {{error_rate}}% |
{{/each}}

{{#if result_count == 0}}
*No API request data this week.*
{{/if}}`,
    send_condition: 'if_results',
    condition_threshold: null,
    compare_offset: null,
    app_scope: 'hey-youre-hired'
  }
];

console.log('Creating HYH Weekly Reports...\n');
console.log(`Recipients: ${RECIPIENTS}`);
console.log(`Schedule: ${SUNDAY_9AM_CRON} (Sunday 9am EST)\n`);

// Check if reports already exist
const existingReports = db.prepare(`
  SELECT name FROM scheduled_reports
  WHERE app_scope = 'hey-youre-hired' AND name LIKE 'HYH Weekly%'
`).all() as { name: string }[];

if (existingReports.length > 0) {
  console.log('Found existing HYH Weekly reports:');
  existingReports.forEach(r => console.log(`  - ${r.name}`));
  console.log('\nDeleting existing reports to recreate...');

  db.prepare(`
    DELETE FROM scheduled_reports
    WHERE app_scope = 'hey-youre-hired' AND name LIKE 'HYH Weekly%'
  `).run();
}

// Insert new reports
const insertStmt = db.prepare(`
  INSERT INTO scheduled_reports (
    id, name, description, query, schedule, recipients, format,
    attachment_format, subject_template, message_template,
    send_condition, condition_threshold, compare_offset,
    app_scope, enabled, created_at
  ) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, 1, datetime('now')
  )
`);

for (const report of reports) {
  console.log(`Creating: ${report.name}`);

  insertStmt.run(
    report.id,
    report.name,
    report.description,
    report.query,
    report.schedule,
    report.recipients,
    report.format,
    report.attachment_format,
    report.subject_template,
    report.message_template,
    report.send_condition,
    report.condition_threshold,
    report.compare_offset,
    report.app_scope
  );

  console.log(`  ✓ Created (ID: ${report.id})`);
}

console.log(`\n✅ Created ${reports.length} HYH Weekly Reports`);
console.log('\nTo trigger a report immediately:');
console.log('  curl -X POST http://localhost:4000/api/reports/{id}/trigger');
console.log('\nReport IDs:');
reports.forEach(r => console.log(`  ${r.name}: ${r.id}`));

db.close();
